module.exports = {
      content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
      corePlugins: {
            aspectRatio: false,
      },
      theme: {
            screens: {
                  xs: '560px',
                  sm: '640px',
                  md: '768px',
                  lg: '976px',
                  xl: '1440px',
            },
            container: {
                  center: true,
            },
            extend: {
                  colors: {
                        fond: '#18163c',
                        fond2: '#1e1c44',
                        fondnoir: '#050811',
                        rose: '#ee4b98',
                        blanc10: 'rgba(255,255,255, .1)',
                        noir10: 'rgba(0,0,0, .1)',
                  },
                  spacing: {
                        '10px': '10px',
                        '20px': '20px',
                        '30px': '30px',
                        '40px': '40px',
                        '50px': '50px',
                        '60px': '60px',
                        '70px': '70px',
                        '80px': '80px',
                        '90px': '90px',
                        '100px': '100px',
                        '120px': '120px',
                        '140px': '140px',
                        '160px': '160px',
                        '180px': '180px',
                        '200px': '200px',
                        '240px': '240px',
                        '280px': '280px',
                        '300px': '300px',
                        '400px': '400px',
                        '500px': '500px',
                        '10vh': '10vh',
                        '20vh': '20vh',
                        '30vh': '30vh',
                        '40vh': '40vh',
                        '50vh': '50vh',
                        '60vh': '60vh',
                        '70vh': '70vh',
                        '80vh': '80vh',
                        '90vh': '90vh',
                        '100vh': '100vh',
                  },
            },
      },
      plugins: [require('@tailwindcss/forms'), require('@tailwindcss/aspect-ratio')],
}
